### PR TITLE
Improved the test code coverage of the opensrp-client-immunization library

### PR DESCRIPTION
**Pull request by kaderchowdhury**
Worked on improving the test code coverage of the opensrp-client-immunization library

### CODE REVIEW

**Comment by raihan-mpower** [comment]
@keymane  codacy is giving issues related to asser as before in https://www.codacy.com/app/OpenSRP/opensrp-client-immunization/pullRequest?prid=1053302
also some empty methods are reported by codacy, we used them for classes to stub or for shadow purposes. Also constructors for shadows are reported by codacy for having __ preceding and following them , we would need them to stub the constructors of custom Views.

**Comment by raihan-mpower** [comment]
@keymane this is good enough to be merged to master

**Comment by pld** [comment]
@kaderchowdhury please change the title of this PR to describe the issue it addresses

**Comment by raihan-mpower** [comment]
@pld made changes to the title of the PR

**Pull request merged**
